### ISSUE TITLE
Gui Load default resource

### ISSUE THREAD

**Issue by MasonJohnHawver-UMN** [MasonJohnHawver42/Galaga#1]
Create a way for a default resource to be loaded from the gui, and to be able to name it.
Thanks

**Comment by MasonJohnHawver42** [comment]
You can implement this in editor/cache_register.hpp and editor/cache_gui.hpp add function ptrs to the widget helper and in the display widget use them to set up a basic set string field and a load resource button - it would be nice if it set this to the viewed resource, but in reality there whould be a loader widget for each cache.

**Comment by MasonJohnHawver42** [comment]
is this good enough to close

**Comment by MasonJohnHawver-UMN** [comment]
Whoops you can close the issue now

**Comment by MasonJohnHawver42** [comment]
okay
